### ISSUE TITLE
shared_functions folder is missing?

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-common-functions#2]
shared_functions folder is missing from components/esp-homekit-functions folder?

**Comment by toshibochan** [comment]
make: Entering directory '/home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/src'
/home/user/projects/esp-open-rtos/common.mk:223: /home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/components/esp-homekit-common-functions/shared_functions/component.mk: No such file or directory
make: *** No rule to make target '/home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/components/esp-homekit-common-functions/shared_functions/component.mk'.  Stop.
make: Leaving directory '/home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/src'

**Comment by maccoylton** [comment]
try executing git submodule update --init --recursive

**Comment by toshibochan** [comment]
I did but only folder is missing is shared_functions

**Comment by maccoylton** [comment]
Does this folder exist:- 

/home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/components/esp-homekit-common-functions

**Comment by toshibochan** [comment]
Yes. But I don’t see shared_functions inside.

**Comment by toshibochan** [comment]
The led strip I was able to make no problem but not sonoff. But led strip have problem to add to home app

**Comment by maccoylton** [comment]
Sonoff-basic has been updated to the latest version

**Comment by toshibochan** [comment]
Thank you so much! I will try later.
